[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/user/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/user/login.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/user/index.html"
  status = 200
